"""
Django settings for roboter project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import djcelery
import subprocess
import platform
from configparser import RawConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
config = RawConfigParser()

config.read(BASE_DIR + "/roboter/settings/settings_" + ".ini")


MONGO_IP=config.get('MONGO', 'MONGO_IP')
MONGO_DB_NAME=config.get('MONGO', 'MONGO_DB_NAME')

MYSQL_IP=config.get('MYSQL', 'MYSQL_IP')
MYSQL_PORT=config.get('MYSQL', 'MYSQL_PORT')
MYSQL_DB_NAME=config.get('MYSQL', 'MYSQL_DB_NAME')
MYSQL_USRE=config.get('MYSQL', 'MYSQL_USRE')
MYSQL_PWD=config.get('MYSQL', 'MYSQL_PWD')


MongoDB_config={
    "site":{
        "host":"%s" %MONGO_IP,
        "dbname":"%s" %MONGO_DB_NAME
    },
}
DATABASES={
    'default':{
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': '%s' %MYSQL_DB_NAME, 
        'USER': '%s' %MYSQL_USRE, 
        'PASSWORD': '%s' %MYSQL_PWD, 
        'HOST': '%s' %MYSQL_IP, 
        'PORT': '%s' %MYSQL_PORT
    }
}


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

