"""
Django settings for roboter project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from configparser import RawConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.getcwd()


config = RawConfigParser()
config.read(BASE_DIR + "/cie/config/settings" + ".ini")

# SSH setting
SSH_HOST = config.get('SSH', 'SSH_HOST')
SSH_PORT = config.get('SSH', 'SSH_PORT')
SSH_USER = config.get('SSH', 'SSH_USER')
SSH_PASSWORD = config.get('SSH', 'SSH_PASSWORD')
SSH_PKEY = config.get('SSH', 'SSH_PKEY')

# monggo settting

MONGO_DB_NAME = config.get('MONGO', 'MONGO_DB_NAME')
MONGO_DB_HOST = config.get('MONGO', 'MONGO_DB_HOST')
MONGO_DB_PORT = config.get('MONGO', 'MONGO_DB_PORT')
MONGO_DB_USER = config.get('MONGO', 'MONGO_DB_USER')
MONGO_DB_PASSWORD = config.get('MONGO', 'MONGO_DB_PASSWORD')
MONGO_DB_LOCAL = config.get('MONGO', 'MONGO_DB_LOCAL')


MongoDB_CONFIG={
    "dbname":"%s" %MONGO_DB_NAME,
    "host":"%s" %MONGO_DB_HOST,
    "port":int(MONGO_DB_PORT),
    "user":"%s" %MONGO_DB_USER,
    "password":"%s" %MONGO_DB_PASSWORD,
    "local":"%s" %MONGO_DB_LOCAL,
    "ssh_host":"%s" %SSH_HOST,
    "ssh_port":int(SSH_PORT),
    "ssh_user":"%s" %SSH_USER,
    "ssh_password":"%s" %SSH_PASSWORD,
    "ssh_private_key":"%s" %SSH_PKEY
}

# mysql setting
MYSQL_HOST=config.get('MYSQL', 'MYSQL_HOST')
MYSQL_PORT=config.get('MYSQL', 'MYSQL_PORT')
MYSQL_DB_NAME=config.get('MYSQL', 'MYSQL_DB_NAME')
MYSQL_USRE=config.get('MYSQL', 'MYSQL_USRE')
MYSQL_PWD=config.get('MYSQL', 'MYSQL_PWD')

MYSQL_CONFIG={
    'host': '%s' %MYSQL_HOST,
    'port':int(MYSQL_PORT),
    'dbname': '%s' %MYSQL_DB_NAME,
    'user': '%s' %MYSQL_USRE,
    'password': '%s' %MYSQL_PWD,
    "ssh_host":"%s" %SSH_HOST,
    "ssh_port":int(SSH_PORT),
    "ssh_user":"%s" %SSH_USER,
    "ssh_password":"%s" %SSH_PASSWORD,
    "ssh_private_key":"%s" %SSH_PKEY
}


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

